Disable `options` in management/commands/celery.py
Commented out a few lines that cause the following error when
trying to re/start celery worker:
```
TypeError: can only concatenate list (not "tuple") to list
```
Best solution is to ditch django-celery altogether and upgrade
to Celery 3.* or 4 but for some reason that's not an easy upgrade
if you use Redis as a broker as we do.